#!/usr/bin/env bash
# This script installs and starts the Nginx web server and sets up a custom page

# Update package lists
apt-get update

# Install Nginx
apt-get install nginx -y

# Start Nginx service
service nginx start

# Create a custom HTML file
echo 'Hello World!' > /var/www/html/index.html
