#!/bin/bash

# Ensure script is run as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit
fi

# Replace the default server block configuration for /redirect_me redirection
sed -i '0,/^}$/ s|^}$|\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n}|' /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
service nginx restart
