#!/usr/bin/env bash
# This script displays "Best School" 10 times,
# but for the 9th iteration, displays "Best School" and then "Hi" on a new line.

BestSchool=1
while [ $BestSchool -le 10 ]; do
    if [ $BestSchool -eq 9 ]; then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi
    ((BestSchool++))
done

