#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes.

hour=0

while [ $hour -lt 13 ]; do
  echo -e "Hour: $hour\n"  
  minute=1
  while [ $minute -lt 60 ]; do
    echo -n "$minute "  
    minute=$((minute + 1))
  done
  echo 
  hour=$((hour + 1))
done

